# agones-gameserver-reader-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: comfyui-agones-sdk-access
subjects:
- kind: ServiceAccount
  name: comfyui-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: agones-controller
  apiGroup: rbac.authorization.k8s.io
